### ISSUE TITLE
Vercel 500 Internal Server Error Issue

### ISSUE THREAD

**Issue by darkmastermindz** [domeccleston/sharegpt#31]
I'm getting back 500 Internal Server error from Vercel with sharegpt url 

Platform: macOS Edge Version 108.0.1462.54 (Official build) (arm64)
ShareGPT Version (commit): b122b13

Console logs the following:

> tuZa2el:1  GET https://sharegpt.com/c/tuZa2el 500
main-58851298adf1f044.js:1 
        
>POST https://vitals.vercel-insights.com/v1/vitals net::ERR_BLOCKED_BY_CLIENT
>l @ main-58851298adf1f044.js:1
>(anonymous) @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
i @ main-58851298adf1f044.js:1
P @ main-58851298adf1f044.js:1
s @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
uU @ framework-3b5a00d5d7e8d93b.js:9
oV @ framework-3b5a00d5d7e8d93b.js:9
o @ framework-3b5a00d5d7e8d93b.js:9
x @ framework-3b5a00d5d7e8d93b.js:33
T @ framework-3b5a00d5d7e8d93b.js:33
VM65 content_script.js:1 
        
 >Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM65 content_script.js:1:1)
main-58851298adf1f044.js:1 
        
> POST https://vitals.vercel-insights.com/v1/vitals net::ERR_BLOCKED_BY_CLIENT
l @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
setTimeout (async)
e @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
load (async)
e @ main-58851298adf1f044.js:1
G @ main-58851298adf1f044.js:1
s @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
uU @ framework-3b5a00d5d7e8d93b.js:9
oV @ framework-3b5a00d5d7e8d93b.js:9
o @ framework-3b5a00d5d7e8d93b.js:9
x @ framework-3b5a00d5d7e8d93b.js:33
T @ framework-3b5a00d5d7e8d93b.js:33
VM81 content_script.js:1 
        
>Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM81 content_script.js:1:1)
VM84 content_script.js:1 
        
>Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM84 content_script.js:1:1)
VM87 content_script.js:1 
        
>Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM87 content_script.js:1:1)
main-58851298adf1f044.js:1 
        
> POST https://vitals.vercel-insights.com/v1/vitals net::ERR_BLOCKED_BY_CLIENT
l @ main-58851298adf1f044.js:1
a @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
r @ main-58851298adf1f044.js:1
main-58851298adf1f044.js:1 
        
>POST https://vitals.vercel-insights.com/v1/vitals net::ERR_BLOCKED_BY_CLIENT
l @ main-58851298adf1f044.js:1
(anonymous) @ main-58851298adf1f044.js:1
s @ main-58851298adf1f044.js:1
r @ main-58851298adf1f044.js:1
content_script.js:1 
        
>Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at content_script.js:1:1)

**Comment by domeccleston** [comment]
Thanks for flagging @darkmastermindz - I'm waiting for Chrome to approve a new version with a fix for this. It should be released by tomorrow, judging by previous release times. Will keep this open until then.
